<a href="https://colab.research.google.com/github/BhavikDudhrejiya/Natural-Language-Processing/blob/main/NLP_Bag_of_Words2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
import pandas as pd

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

In [28]:
text = '''Essay topics in English can be difficult to come up with. 
While writing essays, many college and high school students face writer’s 
block and have a hard time to think about topics and ideas for an essay. 
In this article, we will list out many good essay topics from different 
categories like argumentative essays, essays on technology, environment 
essays for students from 5th, 6th, 7th, 8th grades. Following list of essay 
topics are for all – from kids to college students. We have the largest 
collection of essays. An essay is nothing but a piece of content which is 
written from the perception of writer or author. Essays are similar to a 
story, pamphlet, thesis, etc. The best thing about Essay is you can use any 
type of language – formal or informal. It can biography, the autobiography 
of anyone. Following is a great list of 100 essay topics. We will be adding 
400 more soon!'''

In [24]:
lem = WordNetLemmatizer()
lem.lemmatize

In [29]:
sentences = nltk.sent_tokenize(text)

In [39]:
corpus = []
for i in range(len(sentences)):
  text = re.sub('[^a-zA-Z]', ' ',sentences[i])
  text = text.lower()
  text = text.split()
  text = [lem.lemmatize(word) for word in text if not word in set(stopwords.words('english'))]
  text = ' '.join(text)
  corpus.append(text)

In [40]:
corpus

['essay topic english difficult come',
 'writing essay many college high school student face writer block hard time think topic idea essay',
 'article list many good essay topic different category like argumentative essay essay technology environment essay student th th th th grade',
 'following list essay topic kid college student',
 'largest collection essay',
 'essay nothing piece content written perception writer author',
 'essay similar story pamphlet thesis etc',
 'best thing essay use type language formal informal',
 'biography autobiography anyone',
 'following great list essay topic',
 'adding soon']

In [41]:
vectorizer = CountVectorizer(max_features=1500)

In [43]:
vector = vectorizer.fit_transform(corpus)

In [44]:
vector.shape

(11, 57)

In [52]:
pd.DataFrame(vector.toarray())

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,...,0,0,1,1,1,0,0,1,1,0
2,0,0,1,1,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
6,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,1,1,0,0,0
8,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
10,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0